### ISSUE TITLE
stack test --ta '-p path' fails with an Exception

### ISSUE THREAD

**Issue by mshindo** [vmware/differential-datalog#556]
I followed the instruction as described in https://github.com/vmware/differential-datalog/blob/master/README.md#Installation.

Then, "stack test" command didn't succeed. I am running it on Ubuntu 18.04.3. 

```
% stack test --ta '-p path'
differential-datalog> test (suite: differential-datalog-test, args: -p path)

ddlog tests
  parser tests
    path:          OK (0.04s)
  generated tests
    generate path: FAIL
      Exception: flatc: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
    compiler tests
      path:        SKIP
    unit tests
      path:        SKIP

3 out of 4 tests failed (0.07s)

differential-datalog> Test suite differential-datalog-test failed
Test suite failure for package differential-datalog-0.1.0.0
    differential-datalog-test:  exited with: ExitFailure 1
Logs printed to console
```

**Comment by danbst** [comment]
you are missing `flatbuffers` for some reason.

I've [recently submitted an alternative approach to setup prerequisites](https://github.com/vmware/differential-datalog/pull/555), feel free to try that 
It setups everything to make `stack test --ta '-p path'` working

**Comment by ryzhyk** [comment]
Hi Motonori,

Here is the fragment of `install-dependencies.sh` that installs the FlatBuffers compiler:
https://github.com/vmware/differential-datalog/blob/d223f7c841b9a72c3178943b94ea0bb00740080a/install-dependencies.sh#L23-L27

Having said that, you only need this prerequisite if you plan to invoke DDlog from Java.  `stack test` fails because it is trying to compile the Java API for completeness.  If you only plan to use DDlog via the CLI, you don't need flatbuffers. Use these [instruction](https://github.com/vmware/differential-datalog/blob/master/doc/tutorial/tutorial.md#heavy_exclamation_mark-pro-tip-automating-your-ddlog-workflow) instead.

Leonid

**Comment by mshindo** [comment]
Danylo and Leonid,

Thanks. I managed it to work now! There were a couple of mistakes in the procedure I took, most notably, CLASSPATH was not pointing to the right place. Please let me close this Issue.
