### ISSUE TITLE
Create references to rows (Unique ID's?)

### ISSUE THREAD

**Issue by eqv** [vmware/differential-datalog#766]
Hi, 
I'm trying to create a unique identifier to address a single fact, so that I can track the root cause of further computation. 
To give a bit of background, I have a few Relations (I only use UnseenEdge for now but there are other), and for each entry in those relations I want to create an Event() row. However, there will be another DerivedEvent relation with additional events that derive from those initial rows. I will need to figure out which initial event the final derivations are based on. My approach would be to generate a unique ID stored in the Event relation so that each DerivedEvent can store the id of it's root cause. However I'm unable to figure out how to generate such an ID. I've been trying to use aggregators to get the maximum ID so far.
```
output relation Event(a: u64, id: u32, desc: string)

Event(0,0,"empty").
Event(a, id+1, "foo") :- UnseenEdge(a,b), Event(_,oldid,_), var id = Aggregate((a,b), group_max(oldid)), UnseenEdge(a,b).
 ```
However, I think this approach can't really work as we now keep adding more and more copies of the same event with increasing IDs. Is there any way to get references to existing rows?

I could also imagine to just store the whole Event(a,desc) in the DerivedEvent relation. While that seems like a poor choice in terms of memory usage, this could probably be alleviated by using Inter<T>. 
Any suggestions what would be the best way to express this in DDlog?

**Comment by ryzhyk** [comment]
DDlog does not have a way to auto-generate unique id's, as such id's would depend on the order of adding records, which breaks DDlog's model of computation.

There are several alternatives you can try.

First, you can use the `Ref<>` type to avoid copying:

```
output relation &Event(a: u64, desc: string) // The `&` syntax means that values will be stored by reference.

Event[Event{0,"empty"}.ref_new()].
Event[Event{a, "foo"}.ref_new()] :- UnseenEdge(a,b).
```

Alternatively, you can use `Intern<>` instead of `Ref`, as you suggested.  `Interned` objects are slightly more expensive to create (as they involve computing a hash), but they are much faster to aggregate or join by, since comparing two interned objects is simple pointer comparison:

```
typedef Event = Event{a: u64, des: string}

output relation Event[Intern<Event>]

Event[Event{0,"empty"}.intern()].
Event[Event{a, "foo"}.ref_new()] :- UnseenEdge(a,b).
```

Both `Ref` and `Intern` approaches have an important advantage: they not only identify an `Event` record, but also allow accessing its value without having to join with the `Event` table every time, as you would have if you used event ids.

There are two more options I want to mention for the sake of completeness:

1. Assuming that `Event`'s correspond 1-to-1 to `UnseenEdge` records, and that `UnseenEdge` is an input relation, you can add a unique id field to `UnseenEdge` and propagate it to `Event`.

2. Finally, you can use a cryptographic hash of a record's fields as its unique id. We no longer have a cryptographic hash library, but it's not hard to add one.

**Comment by ryzhyk** [comment]
Assuming you go with the interning option (`Ref` is the same):

```
relation DerivedEvent(foo: bool, bar: string, evt: Intern<Event>)

DerivedEvent(true, descr, e) :- 
     e in &Event(.a = 5, .descr = descr). // variable `e` is bound to the value of the entire record of type `Intern<Event>`
                                                             // the &-syntax opens up the record and lets you pattern-match and bind its individual fields.
```

**Comment by eqv** [comment]
Thanks for taking the time to write this extensive response, I really appreciate the time you take to help me using DDLog!
I will probably experiment with Ref and Intern then to see which is faster. 1) Is unfortunately not the case. I wonder: does 2) offer any advantages over the Intern<T>  solution? Doesn't Intern<T> basically do the same thing with a non-cryptographic hash and a hash table lookup to avoid collisions?  

Is there a difference between `e in &Event(.a=5)` and `e@Event{.a=5}`?

**Comment by ryzhyk** [comment]
>  2) offer any advantages over the Intern solution?

Not really.  I only listed it for completeness.

> Doesn't Intern basically do the same thing with a non-cryptographic hash and a hash table lookup to avoid collisions?

Exactly.

> Is there a difference between e in &Event(.a=5) and e@Event{.a=5}

Same thing, except I think the `@` syntax would have to be slightly different in this case: `Event[e @ &Event{.a = 5}]`.

Anyways, I like the `in` syntax more when binding entire records.

**Comment by eqv** [comment]
Oh right, because we are not binding a matching field, but the whole record. Makes sense. Thanks!

**Comment by ryzhyk** [comment]
> I will probably experiment with Ref and Intern then to see which is faster.

It's really a function of how you use them. As soon as you start using the value as a join key or a group-by argument  in  aggregation, `Intern` will be significantly more efficient.

Both `Ref` and `Intern` have an important caveat that cyclic references are not allowed.
