### ISSUE TITLE
[Question]: why does the dataset need to be in memory?

### ISSUE THREAD

**Issue by ananis25** [vmware/differential-datalog#776]
I apologize if github is not the right place to ask questions. The DDlog documentation mentions this. 
```
In-memory: DDlog stores and processes data in memory. In a typical use case, a DDlog program is used in conjunction with a persistent database, 
with database records being fed to DDlog as ground facts and the derived facts computed by DDlog being written back to the database.
```
Could you please explain what really drives the need for DDlog computation to keep all the data in memory? Could it also be used with a disk based sqlite table?

**Use-case**:
I'm curious if DDlog could be used to write something like a relational cache in front of a postgres-like database, or say a streaming version of sqlite. For example: 
* The main database has 2 large tables A and B, one or both of which get updated frequently.
* Queries generally involve a join between these two, once for each active user and need to be refetched after each update. 

I get around this by implementing a caching layer in front of postgres. Cache the result of the table join the first time, and passing each database update through python code to update that join result. Clearly, it doesn't work as queries get more complex.

Thank you for the work on this.

**Comment by ryzhyk** [comment]
@ananis25 , you may want to look into https://materialize.io/, which is built on the same technology as DDlog, but specializes on integration with SQL databases.

DDlog can consume inputs from and generate outputs to any persistent database; it's just a matter of implementing adapters. In fact this is how it is used in most applications; however its own internal indexes are stored in memory, because this is how the differential dataflow system that we are built on works (mostly for performance reasons).

Is your concern that the tables are too large to index in memory or is it just about being able to connect DDlog inputs/outputs to a database?

**Comment by ananis25** [comment]
Thank you for the pointer to Materialize. Their [post](https://materialize.io/blog-rocksdb/) says storage can't be outsourced  to another engine for streaming performance. 

```
Is your concern that the tables are too large to index in memory or is it just about being able to connect DDlog inputs/outputs to a database?
```
The first one really, though I assume the DDlog/differential-dataflow engine probably runs compaction to keep memory usage low too. Hosting the entire table in memory will need a really beefy instance type.
