### ISSUE TITLE
Question: The performance seems significantly slow compared with DD

### ISSUE THREAD

**Issue by yueshangzuo** [vmware/differential-datalog#816]
Hi there,

I run some tests and find that the performance of DDlog seems significantly slow compared with directly written in DD,
I list the test cases below, is there any help?

This is a simple datalog program with a single join.
```
input relation TABLE(a1: u32, a2: u32)
output relation OUTPUT(b1: u32, b2: u32)

OUTPUT(a1, a2) :-
    TABLE(c, a1),
    TABLE(c, a2).
```

And I generate the inputs with a Python script.
```
import sys

def generate(n=10):
    # print('profile cpu on;')
    print('start;')
    for i in range(1, n):
        print('insert TABLE({}, {}),'.format(i//2, i))
    print('commit;')
    # print('profile;')
    # print('dump OUTPUT;')

if __name__ == '__main__':
    if len(sys.argv) > 1:
        generate(int(sys.argv[1]))
```

Then I rewrite the same logic with DD.
```
timely::execute_from_args(std::env::args(), move |worker| {
    let mut input = InputSession::new();
    let index = worker.index();

    worker.dataflow(|scope| {
        let table = input.to_collection(scope);
        table.join_map(&table, |_k, &a, &b| (a, b));
    });

    let size = std::env::args().nth(1).unwrap().parse().unwrap();

    if index == 0 {
        input.advance_to(0);
        for i in 1 .. size {
            input.insert((i/2, i));
        }
    }

}).expect("Computation terminated abnormally");
```

But the speed of DD is an order of magnitude faster than DDlog, in my computer that is 2.9s vs 36.7s.
```
# DD with version 0.11.0
time cargo run --release 10000000 -w1
real    0m2.878s
user    0m2.341s
sys     0m0.549s

# DDlog with version 0.30.0
time ./target/release/parallel_test_cli < ../data/parallel_test.dat -w1
real    0m36.657s
user    0m38.049s
sys     0m3.703s
```

I know the comparison in this test is not fair, that DDlog program needs to load data from disk with extra IO, **Question 1: Is there any other reason that can explain this huge difference?**
Also, I run the profile for DDlog, the result shows the `InspectBatch` may be the main reason for the lower speed, **Question 2: What is the `InspectBatch` about, can we do some optimizations here?**
```
Profile:

Arrangement size profile
19999997      Arrange: OUTPUT.threshold_total 17
9999999      Arrange: (TABLE{.a1=(_0: bit<32>), .a2=(_: bit<32>)}: TABLE) /*join*/ 6
0      Arrange: _ /*join*/ 26

Arrangement peak sizes
19999997      Arrange: OUTPUT.threshold_total 17
9999999      Arrange: (TABLE{.a1=(_0: bit<32>), .a2=(_: bit<32>)}: TABLE) /*join*/ 6
0      Arrange: _ /*join*/ 26

CPU profile
    13s118742us (       25calls)     Dataflow: 0
       5s115676us (        2calls)     InspectBatch: inspect 0 34
       1s983740us (       21calls)     Arrange: OUTPUT.threshold_total 17
       1s975440us (        2calls)     Consolidate: consolidate 0 30
       1s246076us (       20calls)     Join: TABLE[(TABLE{.a1=(c: bit<32>), .a2=(a1: bit<32>)}: TABLE)], TABLE[(TABLE{.a1=(c: bit<32>), .a2=(a2: bit<32>)}: TABLE)] 9
       1s073475us (        2calls)     Arrange: (TABLE{.a1=(_0: bit<32>), .a2=(_: bit<32>)}: TABLE) /*join*/ 6
       0s532578us (        2calls)     ThresholdTotal: OUTPUT.threshold_total 19
       0s404159us (        2calls)     FlatMap: (TABLE{.a1=(_0: bit<32>), .a2=(_: bit<32>)}: TABLE) /*join*/ 4
       0s385421us (        2calls)     AsCollection: consolidate 0 32
       0s139657us (       21calls)     Map: OUTPUT.threshold_total 15
       0s138742us (        2calls)     Map: consolidate 0 28
       0s110311us (        2calls)     Probe: probe 0 36
       0s008745us (       21calls)     Concatenate: concatenate rules for OUTPUT 12
       0s004383us (        2calls)     Concatenate: concatenate rules for TABLE 2
       0s000000us (        1calls)     Input: 1
       0s000000us (        0calls)     FlatMap: _ /*join*/ 24
       0s000000us (        0calls)     Concatenate: concatenate rules for __Null 22
       0s000000us (        0calls)     Arrange: _ /*join*/ 26
       0s000000us (        0calls)     Input: 21
       0s000000us (        0calls)     AsCollection: 38
       0s000000us (        0calls)     Input: 8
       0s000000us (        0calls)     Probe: 40
```

Thanks!

**Comment by ryzhyk** [comment]
On my machine your program takes 25.4s, which includes 11.4 seconds parsing the input file.  DDlog's text format is mainly used for debugging and is not designed for parsing speed.

Next, we need to make a few changes to the DDlog program to make it an apples-to-apples comparison.  First, by default DDlog enforces set semantics on both input and output relations. For input relations this means that DDlog eliminates duplicate inserts and deletes by storing a cached copy of inputs.  For outputs, it uses the `threshold_total` operator to eliminate duplicates.  To disable this behavior, replace `relation` with `stream` in your DDlog code.

In addition to `threshold_total`, DDLog performs two more processing steps on its output: first, it applies the `consolidare` operator to it to eliminate mutually compensating inserts and deletes, which most users prefer not to see. This is the `consolidate` entry in your profile.  Finally, it uses the `inspect` operator to invoke an internal callback for each output record produced by the program (the `InspectBatch` entry in the log). The latter is a bit expensive, since your program produces 20 million output records. 

In contrast, your code simply drops output on the floor.  To achieve the same in DDlog, I slightly modified the program to compute the join, but then drop the result so that the amount of work DDlog does is roughly the same as your DD example.  Here is the resulting program:

```
input relation TABLE(a1: u32, a2: u32)
output relation OUTPUT(b1: u32, b2: u32)

OUTPUT(a1, a2) :-
    TABLE(c, a1),
    TABLE(c, a2),
    false. // Drop the result of the join
```

and here is its CPU profile, which is roughly comparable to that of pure DD:

```
CPU profile
     1s733285us (        4calls)     Dataflow: 0
       0s867372us (        2calls)     Arrange: (TABLE{.a1=(_0: bit<32>), .a2=(_: bit<32>)}: TABLE) /*join*/ 6
       0s590498us (        2calls)     Join: TABLE[(TABLE{.a1=(c: bit<32>), .a2=(a1: bit<32>)}: TABLE)], TABLE[(TABLE{.a1=(c: bit<32>), .a2=(a2: bit<32>)}: TABLE)] 9
       0s271359us (        2calls)     FlatMap: (TABLE{.a1=(_0: bit<32>), .a2=(_: bit<32>)}: TABLE) /*join*/ 4
       0s003996us (        2calls)     Concatenate: concatenate rules for TABLE 2
       0s000007us (        1calls)     Consolidate: consolidate 0 24
       0s000001us (        1calls)     Concatenate: concatenate rules for OUTPUT 12
       0s000001us (        1calls)     Probe: probe 0 30
       0s000000us (        1calls)     Input: 1
       0s000000us (        0calls)     Input: 15
       0s000000us (        0calls)     AsCollection: consolidate 0 26
       0s000000us (        0calls)     AsCollection: 32
       0s000000us (        0calls)     Concatenate: concatenate rules for __Null 16
       0s000000us (        0calls)     FlatMap: _ /*join*/ 18
       0s000000us (        0calls)     Arrange: _ /*join*/ 20
       0s000000us (        0calls)     Map: consolidate 0 22
       0s000000us (        0calls)     InspectBatch: inspect 0 28
       0s000000us (        0calls)     Probe: 34
       0s000000us (        0calls)     Input: 8
```

As you can see the only real cost you pay here is arranging and joining the input relation with itself, which is precisely what your DD code does too.

**Comment by ryzhyk** [comment]
PS.  I'm not sure your DD code is actually correct.  You may want to extend it to output the result of the join to make sure it does what you expect and propagates the data all the way through the pipeline.

**Comment by ryzhyk** [comment]
PPS.  In practice, the various overheads introduced by DDlog, even if you don't disable them as I did above, are less significant in most real-world examples; however they are essential to the ergonomics of writing applications that interact with an incremental computation.

**Comment by yueshangzuo** [comment]
Thanks for your detailed reply! I learn more about DDlog now. I just omitted the output of the dataflow in DD code for the comparison, thanks for your reminding.
