### ISSUE TITLE
Can i speed up the compilation ?

### ISSUE THREAD

**Issue by jinyang175** [vmware/differential-datalog#876]
Hi, 

Can I somehow decrease the time it takes the Rust compiler to generate a binary executable?
Currently, it is taking up to 3 minutes to compile. 

Changing `opt-level` to `0` in `Cargo.toml` does not make a significant difference. Any tips?

Thanks!

**Comment by mbudiu-vmw** [comment]
Are you using the latest version of ddlog? Some recent changes were designed to improve *re*compilation time. The first time you compile it is indeed slow, but any changes you make to your program should compile much faster. But indeed, this is often the most time consuming part, and it's not clear we can do much. It's probably because we use heavily generic types in Rust.

**Comment by ryzhyk** [comment]
There are a couple of things you can try. As @mbudiu-vmw said, we made some improvements to speedup incremental re-compilation of Rust code. To take advantage of those, you can try decomposing your DDlog code into modules without circular dependencies.  DDlog will then generate a separate Rust crate for each module.  Of course, this only makes sense if your DDlog program is large enough.

You can also speedup the modify/compile/test cycle by running cargo with the following env variable: `CARGO_PROFILE_RELEASE_OPT_LEVEL="z"`.  The resulting code will execute about 50% more slowly (so you don't want this for benchmarking), but Rust compilation will go much faster.

**Comment by jinyang175** [comment]
Awesome. Yes, I am using the latest version of DDlog. 
Thanks guys, this is very helpful! And thanks for replying so fast!
