### ISSUE TITLE
How to generate a fixed number of iterations? i.e. range iteration

### ISSUE THREAD

**Issue by norcalli** [vmware/differential-datalog#919]
For a particular relation, I'm going to be generating aggregates for monthly values based on two inputs: start, and end.

I can't seem to find an example of how to do a simple range based iteration between two numerical values, like the `start..end` range syntax in Rust.

I could probably make an extern which generates a `Vec` like `generate_for(f: |'A|: 'B, start: 'A, end: 'A): Vec<'B>`, but I'm curious if there's anything like that internally.

(Or perhaps do a `typedef Range = RangeInclusive ` etc.. with all the cases to mirror Rust instead of `start`+`end`.)

**Comment by ryzhyk** [comment]
There is a `range_vec` function in `ddlog_std.dl`. More general range support along the lines or Rust would be nice, but for now this should hopefully do the job for you.

**Comment by norcalli** [comment]
So there is!

Is there any way to avoid the allocation of a Vec, actually? I forgot to mention that in my original question, but within in the context of a relation, it seems like it should be possible to avoid. Also thanks for the speedy response!

**Comment by ryzhyk** [comment]
> but within in the context of a relation, it seems like it should be possible to avoid

Can you clarify what you mean by "within in the context of a relation"? Or perhaps if you could just show an example of code you'd like to be able to write, I might be able to suggest the best way to express it in DDlog.

**Comment by ryzhyk** [comment]
We recently added the ability to implement user-defined iterable objects in DDlog (https://github.com/vmware/differential-datalog/blob/master/doc/tutorial/tutorial.md#iterate_by_ref-and-iterate_by_val); however it requires coding in Rust.  So you may want to start with `range_vec` and later replace it with something more efficient like a `Range` object.

Having said that, if the values you are aggregating are stored as separate records in a relation, then none of this should be necessary, which is why I'd like to look at a concrete example.

**Comment by norcalli** [comment]
Oh wow it was just released. Yeah I think my question is answered by the `iter()` interface actually, combined with FlatMap. What I was trying to achieve was iterating inside of a relation without creating an intermediate vec.
